language: php
php:
  - '7.2'
services:
  - mysql
cache:
  directories:
    - node_modules
    - ~/.npm
    - vendor
git:
  depth: 3
before_install:
  - sudo mysql -e 'create database testing_laravel;'
before_script:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader
  - npm install
script:
  - php artisan migrate:refresh --force
  - php artisan test
notifications:
  email:
    recipients:
      - johannitaarango2@gmail.com
      - larangogon1@uniminuto.edu.co
    on_success: always
    on_failure: always
