language: php
php:
  - '7.2'
services:
  - mysql
cache:
  directories:
    - node_modules
    - ~/.npm
    - vendor
git:
  depth: 3
before_script:
  - composer install --prefer-dist --optimize-autoloader
  - npm install
before_script:
  - cp .env.testing .env
  - sudo mysql -e 'CREATE DATABASE testing_laravel;'
  - php artisan migrate
  - php artisan test
notifications:
  email:
    recipients:
      - johannitaarango2@gmail.com
      - larangogon1@uniminuto.edu.co
    on_success: always
    on_failure: always
