language: php
php:
  - '7.2'
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
script: phpunit
before_script: ./before_script.sh
script: "php run-phpunit.php"
script: vendor/bin/phpunit --configuration phpunit.xml
dist: trusty
services:
  - mysql
cache:
  directories:
    - node_modules
    - ~/.npm
    - vendor

git:
  depth: 3
before_install:
  - mysql -e 'create database laravelTest;'

before_script:
  - composer install --prefer-dist --optimize-autoloader
  - npm install
script:
  - php artisan migrate --force
  - php artisan test
notifications:
    email:
      recipients:
        - johannitaarango2@gmail.com
        - larangogon1@uniminuto.edu.co
      on_success: always
      on_failure: always
