<?php

namespace Tests\Feature;

use App\Cart;
use App\Category;
use App\Color;
use App\Product;
use App\Size;
use App\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ApiTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var Collection|Model|mixed
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(\PermissionsTableSeeder::class);

        $this->user = factory(User::class)->create([
            'active' => 1
        ]);
        $this->user->assignRole('Administrator');
        $this->cart = new Cart();

        $this->cart->user_id = $this->user->id;
        $this->cart->save();
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testApiDestroyTest()
    {
        $products = Product::create([
            'name' => 'nameAPI',
            'description' => 'description',
            'price' => 100000,
            'stock' => 5,
        ]);

        $response = $this->actingAs($this->user, 'api')
            ->deleteJson(route('product.destroy', $products->id), [
                'id' => $products->id
            ]);

        $response
            ->assertStatus(200);

        $this->assertDatabaseMissing('products', [
            'id' => $products->id,
        ]);
    }

    public function testApiIndexTest()
    {
        $response = $this->actingAs($this->user, 'api')
            ->getJson(route('product.index'));

        $response
            ->assertStatus(200);
    }

    public function testUpdate()
    {
        $this->withoutExceptionHandling();
        $this->seed([
            \ColorSeeder::class,
            \SizeSeeder::class,
            \CategorySeeder::class
        ]);
        $product = Product::create([
            'name'        => 'nameApi',
            'description' => 'description',
            'price'       => 5666,
            'stock'       => 5,
        ]);

        $response = $this->actingAs($this->user, 'api')
            ->putJson(route('product.update', $product->id), [
                'name'  => 'nameupApi',
                'stock' => $product->stock,
                'color' => [Color::all()->random()->id],
                'size' => [Size::all()->random()->id],
                'category' => [Category::all()->random()->id]
            ]);

        $response
            ->assertStatus(200);

        $this->assertDatabaseHas('products', [
            'id'  => $product->id,
            'name' => 'nameupApi'
        ]);
    }

    public function testStoreApi(): void
    {
        $this->withoutExceptionHandling();

        $this->seed([
            \ColorSeeder::class,
            \SizeSeeder::class,
            \CategorySeeder::class,
        ]);

        $response = $this->actingAs($this->user, 'api')
            ->postJson(route('product.store'), [
                'name'  => 'newApi',
                'stock' => 56,
                'price' => 23456,
                'description' => 'jdhfbgyebhsabfreahbfgy',
                'color' => [Color::all()->random()->id],
                'size' => [Size::all()->random()->id],
                'category' => [Category::all()->random()->id],
                'img' => '0af47a0f0bb89e7ce4d88f121faea42b.jpg'
            ]);

        $response
            ->assertStatus(200);

        $this->assertDatabaseHas('products', [
            'name'  => 'newApi'
        ]);
    }
}
