<?php

namespace Tests\Feature;

use App\Entities\Cart;
use App\Exports\OrdersExport;
use App\Exports\ProductsExport;
use App\Exports\UsersExport;
use App\Entities\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Maatwebsite\Excel\Facades\Excel;
use Tests\TestCase;

class ExportTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
        $this->withoutMiddleware();

        $this->seed(\PermissionsTableSeeder::class);
        $this->user = factory(User::class)->create();

        $this->user->assignRole('Administrator');

        $this->cart =  new Cart();
        $this->cart->user_id = $this->user->id;
        $this->cart->save();
    }

    /**
     * @test
     */
    public function user_can_download_products_export()
    {
        $this->withoutExceptionHandling();
        Excel::fake();

        $this->actingAs($this->user, 'web')
            ->get('exportProducts');

        Excel::assertDownloaded('products.xlsx', function (ProductsExport $export) {
            // Assert that the correct export is downloaded.
            return true;
        });
    }

    /**
     * @test
     */
    public function user_can_download_users_export()
    {
        $this->withoutExceptionHandling();
        Excel::fake();

        $this->actingAs($this->user, 'web')
            ->get('exportUsers');

        Excel::assertDownloaded('users.xlsx', function (UsersExport $export) {
            // Assert that the correct export is downloaded.
            return true;
        });
    }

    /**
     * @test
     */
    public function user_can_download_orders_export()
    {
        $this->withoutExceptionHandling();
        Excel::fake();

        $this->actingAs($this->user, 'web')
            ->get('exportOrders');

        Excel::assertDownloaded('orders.xlsx', function (OrdersExport $export) {
            // Assert that the correct export is downloaded.
            return true;
        });
    }
}
