<?php

namespace Tests\Feature\Administrator\Payment\Order;

use App\Cart;
use App\Order;
use App\Payment;
use App\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class StoreOrderPayTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(\PermissionsTableSeeder::class);

        $this->user = factory(User::class)->create();
        $this->user->assignRole('Administrator');

        $this->cart = new Cart();
        $this->cart->user_id = $this->user->id;
        $this->cart->save();
    }

    public function testStore(): void
    {
        $this->order = new Order();
        $this->order->user_id = $this->user->id;
        $this->order->total   = $this->user->cart->total = '239844';
        $this->order->save();

        $this->assertDatabaseHas('orders', [
             'total' => '239844'
         ]);
    }

    /**
     * @return Void
     */
    public function testOrderShowv(): Void
    {
        $this->withoutMiddleware();
        $this->withoutExceptionHandling();

        $response = $this->actingAs($this->user)
            ->get(route('orders.showv', $this->user->id));

        $response->assertStatus(200);
    }

    public function testStorePay(): void
    {
        $this->withoutMiddleware();

        $this->order = new Order();

        $this->order->user_id = $this->user->id;
        $this->order->total   = $this->user->cart->total = '239844';
        $this->order->save();

        $this->pay = new Payment();
        $this->pay->order_id    = $this->order->id;
        $this->pay->processUrl  = 'https://test.placetopay.com/redirection/session/401660/f355a2ce680602583c87b9423e5699d8' ;
        $this->pay->requestId   = '401660';
        $this->pay->status      = 'PENDING' ;

        $this->pay->save();

        $this->assertDatabaseHas('payments', [
            'status' => 'PENDING'
        ]);
    }

    public function testUpdatePay(): void
    {
        $this->withoutExceptionHandling();
        $this->withoutMiddleware();

        $this->order = new Order();

        $this->order->user_id = $this->user->id;
        $this->order->total   = $this->user->cart->total = '6778999';

        $this->order->save();

        $this->payment = new Payment();

        $this->payment->order_id    = $this->order->id;
        $this->payment->processUrl  = 'https://test.placetopay.com/redirection/session/401660/f355a2ce680602583c87b9423e5699d8' ;
        $this->payment->requestId   = '401660';
        $this->payment->status      = 'PENDING' ;

        $this->payment->save();

        $response = $this->actingAs($this->user)
            ->put(route('orders.update', $this->order->id), [
                'internalReference' => '1494590937',
                'status'            => 'APPROVED',
                "message"           => 'La petición ha sido aprobada exitosamente',
                'amount'            => '6778999',
                'document'          => '1234566',
                'name'              => 'johanna',
                'email'             => 'johannitaarango@gmail.com',
                'mobile'            => '12345667',
                'locale'            => 'es_CO',
            ]);

        $response
            ->assertStatus(200);

        $this->assertDatabaseHas('orders', [
            'id'  => $this->order->id,
        ]);
    }

    public function testDestroyOrder(): void
    {
        $this->withoutExceptionHandling();

        $this->order = new Order();

        $this->order->id = 4;
        $this->order->user_id = $this->user->id;
        $this->order->total   = $this->user->cart->total = '6778999';

        $this->order->save();

        $this->payment = new Payment();

        $this->payment->order_id    = $this->order->id;
        $this->payment->processUrl  = 'https://test.placetopay.com/redirection/session/412446/41173d8c3e45052f2e61de558f9baeb6' ;
        $this->payment->requestId   = '412446';
        $this->payment->status      = 'APROVED' ;

        $this->payment->save();

        Order::destroy($this->order->id = 4);

        $response = $this->actingAs($this->user)
            ->post(route('orders.reversePay', $this->order->id), [
                'internalReference' => '1495465116',
                'status'            => 'APPROVED',
                "message"           => 'La petición ha sido aprobada exitosamente',
                'amount'            => '6778999',
                'document'          => '1234566',
                'name'              => 'admin',
                'email'             => 'johannitaarango@gmail.com',
                'mobile'            => '12345667',
                'locale'            => 'es_CO',
            ]);

        $response
            ->assertStatus(302);

        $this->assertDatabaseMissing('orders', [
            'id'  => $this->order->id = 4,
        ]);
    }
}
