<?php

namespace Tests\Feature\Administrator\Products;

use App\Entities\Cart;
use App\Entities\Category;
use App\Entities\Color;
use App\Entities\Product;
use App\Entities\Size;
use App\Entities\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CrudProductsTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var Collection|Model|mixed
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed(\PermissionsTableSeeder::class);

        $this->user = factory(User::class)->create([
            'active' => 1
        ]);
        $this->user->assignRole('Administrator');
        $this->cart =  new Cart();

        $this->cart->user_id = $this->user->id;
        $this->cart->save();

        $this->size = factory(Size::class)->create();
        $this->color = factory(Color::class)->create();
        $this->category = factory(Category::class)->create();
    }

    public function testIndex()
    {
        $response = $this->actingAs($this->user, 'web')
            ->get(route('products.index'));

        $response
            ->assertStatus(200)
            ->assertViewHas(['products', 'search'])
            ->assertViewIs('products.index');

        $this->assertAuthenticatedAs($this->user, $guard = null);
    }

    public function testDestroy()
    {
        $products = Product::create([
         'name'        => 'name',
         'description' => 'description',
         'price'       => 100000,
         'stock'       => 5,
        ]);

        $response = $this->actingAs($this->user, 'web')
            ->delete(route('products.destroy', $products->id), [
            'id'  => $products->id
        ]);

        $response
            ->assertStatus(302)
            ->assertRedirect(route('products.index'))
            ->assertSessionHas('success', 'Eliminado Satisfactoriamente !');

        $this->assertDatabaseMissing('products', [
            'id'  => $products->id,
        ]);

        $this->assertAuthenticatedAs($this->user, $guard = null);
    }

    public function testUpdate()
    {
        $product = Product::create([
            'name'        => 'name',
            'description' => 'description',
            'price'       => 5666,
            'stock'       => 5,
        ]);

        $response = $this->actingAs($this->user)
            ->put(route('products.update', $product->id), [
                'name'  => 'nameup',
                'stock' => $product->stock,
                'color' => [$this->color->id],
                'size'  => [$this->size->id]
            ]);

        $response
            ->assertStatus(302)
            ->assertRedirect(route('products.index'))
            ->assertSessionHas('success', 'Producto Editado Satisfactoriamente');

        $this->assertDatabaseHas('products', [
            'id'    => $product->id,
            'name'  => 'nameup',
            'stock' => $product->stock,
        ]);

        $this->assertDatabaseHas('color_product', [
            'product_id' => $product->id,
            'color_id'   => [$this->color->id],
        ]);

        $this->assertDatabaseHas('product_size', [
            'product_id' => $product->id,
            'size_id'    => [$this->size->id],
        ]);
    }

    public function testUpdateErrors()
    {
        $product = factory(Product::class)->create();

        $response = $this->actingAs($this->user)
            ->put(route('products.update', $product->id), []);

        $response->assertSessionHasErrors(['stock',
            'name','color', 'size',
        ]);
    }

    public function testStore(): void
    {
        $response = $this->actingAs($this->user)
            ->post(route('products.store'), [
            'name'        => 'new',
            'stock'       => 56,
            'price'       => 23456,
            'barcode'     => '12324345354565',
            'description' => 'jdhfbgyebhsabfreahbfgy',
            'color'       => [$this->color->id],
            'size'        => [$this->size->id],
            'category'    => [$this->category->id],
            'img'         => '0af47a0f0bb89e7ce4d88f121faea42b.jpg'
        ]);

        $response
            ->assertStatus(302)
            ->assertRedirect(route('products.index'))
            ->assertSessionHas('success', 'producto Creado Satisfactoriamente');

        $this->assertDatabaseHas('products', [
            'name'  => 'new'
        ]);

        $this->assertAuthenticatedAs($this->user, $guard = null);
    }

    public function testStoreErrors(): void
    {
        $response = $this->actingAs($this->user)
            ->post(route('products.store'), []);

        $response
            ->assertSessionHasErrors(['stock',
                'name', 'price',
                'barcode', 'description',
                'img', 'color', 'size', 'category'
            ])
            ->assertStatus(302);
    }

    public function testCreate()
    {
        $response = $this->actingAs($this->user, 'web')
            ->get(route('products.create'));

        $response
            ->assertViewIs('products.create')
            ->assertStatus(200);

        $this->assertAuthenticatedAs($this->user, $guard = null);
    }

    public function testEditView()
    {
        $product = Product::create([
            'name'        => 'new',
            'stock'       => 56,
            'price'       => 23456,
            'barcode'     => '12324345354565',
            'description' => 'jdhfbgyebhsabfreahbfgy',
            'color'       => [$this->color->id],
            'size'        => [$this->size->id],
            'category'    => [$this->category->id],
            'img'         => '0af47a0f0bb89e7ce4d88f121faea42b.jpg'
        ]);

        $response = $this->actingAs($this->user, 'web')
            ->get(route('products.edit', $product->id));

        $response
            ->assertStatus(200)
            ->assertViewHas([
                'product',
                'colors',
                'categories',
                'sizes',
            ])
            ->assertViewIs('products.edit');

        $this->assertAuthenticatedAs($this->user, $guard = null);
    }

    public function testShow()
    {
        $product = Product::create([
            'name'        => 'new',
            'stock'       => 56,
            'price'       => 23456,
            'barcode'     => '1232434535945658',
            'description' => 'jdhfbgyebhsabfreahbfgy',
            'color'       => [$this->color->id],
            'size'        => [$this->size->id],
            'category'    => [$this->category->id],
            'img'         => '0af47a0f0bb89e7ce4d88f121faea42b.jpg',
            'active'      => 1
        ]);

        $response = $this->actingAs($this->user, 'web')
            ->get(route('products.show', $product->id));

        $response
            ->assertStatus(200)
            ->assertViewHas([
                'product',
            ])
            ->assertViewIs('products.show');

        $this->assertAuthenticatedAs($this->user, $guard = null);
    }

    public function testUpdateActive()
    {
        $product = Product::create([
            'name'        => 'name',
            'description' => 'description',
            'price'       => 5666,
            'stock'       => 5,
            'active'      => 0
        ]);

        $response = $this->actingAs($this->user)
            ->get(route('products.active', $product->id), [
                'active' => 1
            ]);

        $response
            ->assertStatus(302)
            ->assertRedirect(route('products.index'))
            ->assertSessionHas('message', 'Estatus del producto Editado Satisfactoriamente !');

        $this->assertDatabaseHas('products', [
            'id'     => $product->id,
            'name'   => 'name',
            'active' => 1
        ]);
    }
}
