<?php

namespace Tests\Feature\Administrator\Payment\Shipping;

use App\Entities\Cart;
use App\Entities\Order;
use App\Entities\Shipping;
use App\Entities\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ShippiendTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed(\PermissionsTableSeeder::class);

        $this->user = factory(User::class)->create([
            'active' => 1
        ]);
        $this->user->assignRole('Administrator');

        $this->cart = new Cart();
        $this->cart->user_id = $this->user->id;
        $this->cart->save();

        $this->order = new Order();
        $this->order->user_id = $this->user->id;
        $this->order->total   = $this->user->cart->total = '239844';
        $this->order->save();
    }

    public function testStatusShippieng(): void
    {
        $this->withoutMiddleware();
        $this->get(route('orders.shippingStatus', $this->order->id))
            ->assertStatus(302);
    }

    public function teststore(): void
    {
        $recipient= new Shipping();

        $recipient->name_recipient      = 'name_recipient';
        $recipient->phone_recipient     = '1223445';
        $recipient->cellphone_recipient = '2334455';
        $recipient->document_recipient  = '122335566';
        $recipient->address_recipient   = 'address_recipient';
        $recipient->email_recipient     = 'camila@gmail.com';
        $recipient->country_recipient   = 'country_recipient';
        $recipient->city_recipient      = 'city_recipient';
        $recipient->order_id            = $this->order->id;

        $recipient->save();

        $response = $this->actingAs($this->user)
            ->post(route('shipping.store', $recipient->id));
        $response
            ->assertStatus(302);

        $this->assertDatabaseHas('shippings', [
            'name_recipient' => 'name_recipient'
        ]);
    }
}
