<?php

namespace Tests\Feature\Administrator\ImportExport;

use App\Entities\Cart;
use App\Entities\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Maatwebsite\Excel\Facades\Excel;
use Tests\TestCase;

class ImportTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed
     */
    private $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withoutMiddleware();

        $this->seed(\PermissionsTableSeeder::class);
        $this->user = factory(User::class)->create();

        $this->user->assignRole('Administrator');

        $this->cart =  new Cart();
        $this->cart->user_id = $this->user->id;
        $this->cart->save();
    }

    /**
     * @test
     */
    public function indexImportProducts()
    {
        $response = $this->actingAs($this->user)
            ->get(route('indexProducts'));

        $response->assertStatus(200)
            ->assertViewIs('imports.indexProducts');

        $this->assertAuthenticatedAs($this->user, $guard = null);
    }

    /**
     * @test
     */
    public function indexImportUsers()
    {
        $response = $this->actingAs($this->user)
            ->get(route('imports.index'));

        $response->assertStatus(200)
            ->assertViewIs('imports.index');

        $this->assertAuthenticatedAs($this->user, $guard = null);
    }
}
